---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/greatti6/public_html/
    - /bin/cp -R /home3/greatti6/repositories/gr8timehub.io.git/img $DEPLOYPATH
    - /bin/cp -R /home3/greatti6/repositories/gr8timehub.io.git/scripts $DEPLOYPATH
    - /bin/cp -R /home3/greatti6/repositories/gr8timehub.io.git/sound $DEPLOYPATH